#pragma once

#include <vulkan/vulkan.h>
#include <cstdint>

namespace vk
{

using Instance = VkInstance;
using PhysicalDevice = VkPhysicalDevice;
using Device = VkDevice;
using Queue = VkQueue;
using CommandBuffer = VkCommandBuffer;
using DeviceMemory = VkDeviceMemory;
using CommandPool = VkCommandPool;
using Buffer = VkBuffer;
using BufferView = VkBufferView;
using Image = VkImage;
using ImageView = VkImageView;
using ShaderModule = VkShaderModule;
using Pipeline = VkPipeline;
using PipelineLayout = VkPipelineLayout;
using Sampler = VkSampler;
using DescriptorSet = VkDescriptorSet;
using DescriptorSetLayout = VkDescriptorSetLayout;
using DescriptorPool = VkDescriptorPool;
using Fence = VkFence;
using Semaphore = VkSemaphore;
using Event = VkEvent;
using QueryPool = VkQueryPool;
using Framebuffer = VkFramebuffer;
using RenderPass = VkRenderPass;
using PipelineCache = VkPipelineCache;
using DisplayKHR = VkDisplayKHR;
using DisplayModeKHR = VkDisplayModeKHR;
using SurfaceKHR = VkSurfaceKHR;
using SwapchainKHR = VkSwapchainKHR;
using DebugReportCallbackEXT = VkDebugReportCallbackEXT;


using VkSampleMask = uint32_t;
using VkBool32 = uint32_t;
using VkFlags = uint32_t;
using VkDeviceSize = uint64_t;


enum class AttachmentLoadOp : std::int32_t;
enum class AttachmentStoreOp : std::int32_t;
enum class BlendFactor : std::int32_t;
enum class BlendOp : std::int32_t;
enum class BorderColor : std::int32_t;
enum class FramebufferCreateFlagBits : std::int32_t;
enum class QueryPoolCreateFlagBits : std::int32_t;
enum class RenderPassCreateFlagBits : std::int32_t;
enum class SamplerCreateFlagBits : std::int32_t;
enum class PipelineCacheHeaderVersion : std::int32_t;
enum class PipelineLayoutCreateFlagBits : std::int32_t;
enum class PipelineCacheCreateFlagBits : std::int32_t;
enum class PipelineDepthStencilStateCreateFlagBits : std::int32_t;
enum class PipelineDynamicStateCreateFlagBits : std::int32_t;
enum class PipelineColorBlendStateCreateFlagBits : std::int32_t;
enum class PipelineMultisampleStateCreateFlagBits : std::int32_t;
enum class PipelineRasterizationStateCreateFlagBits : std::int32_t;
enum class PipelineViewportStateCreateFlagBits : std::int32_t;
enum class PipelineTessellationStateCreateFlagBits : std::int32_t;
enum class PipelineInputAssemblyStateCreateFlagBits : std::int32_t;
enum class PipelineVertexInputStateCreateFlagBits : std::int32_t;
enum class PipelineShaderStageCreateFlagBits : std::int32_t;
enum class DescriptorSetLayoutCreateFlagBits : std::int32_t;
enum class BufferViewCreateFlagBits : std::int32_t;
enum class InstanceCreateFlagBits : std::int32_t;
enum class DeviceQueueCreateFlagBits : std::int32_t;
enum class BufferCreateFlagBits : std::int32_t;
enum class BufferUsageFlagBits : std::int32_t;
enum class ColorComponentFlagBits : std::int32_t;
enum class ComponentSwizzle : std::int32_t;
enum class CommandPoolCreateFlagBits : std::int32_t;
enum class CommandPoolResetFlagBits : std::int32_t;
enum class CommandBufferResetFlagBits : std::int32_t;
enum class CommandBufferLevel : std::int32_t;
enum class CommandBufferUsageFlagBits : std::int32_t;
enum class CompareOp : std::int32_t;
enum class CullModeFlagBits : std::int32_t;
enum class DescriptorType : std::int32_t;
enum class DeviceCreateFlagBits : std::int32_t;
enum class DynamicState : std::int32_t;
enum class FenceCreateFlagBits : std::int32_t;
enum class PolygonMode : std::int32_t;
enum class Format : std::int32_t;
enum class FormatFeatureFlagBits : std::int32_t;
enum class FrontFace : std::int32_t;
enum class ImageAspectFlagBits : std::int32_t;
enum class ImageCreateFlagBits : std::int32_t;
enum class ImageLayout : std::int32_t;
enum class ImageTiling : std::int32_t;
enum class ImageType : std::int32_t;
enum class ImageUsageFlagBits : std::int32_t;
enum class ImageViewType : std::int32_t;
enum class SharingMode : std::int32_t;
enum class IndexType : std::int32_t;
enum class LogicOp : std::int32_t;
enum class MemoryHeapFlagBits : std::int32_t;
enum class AccessFlagBits : std::int32_t;
enum class MemoryPropertyFlagBits : std::int32_t;
enum class PhysicalDeviceType : std::int32_t;
enum class PipelineBindPoint : std::int32_t;
enum class PipelineCreateFlagBits : std::int32_t;
enum class PrimitiveTopology : std::int32_t;
enum class QueryControlFlagBits : std::int32_t;
enum class QueryPipelineStatisticFlagBits : std::int32_t;
enum class QueryResultFlagBits : std::int32_t;
enum class QueryType : std::int32_t;
enum class QueueFlagBits : std::int32_t;
enum class SubpassContents : std::int32_t;
enum class Result : std::int32_t;
enum class ShaderStageFlagBits : std::int32_t;
enum class SparseMemoryBindFlagBits : std::int32_t;
enum class StencilFaceFlagBits : std::int32_t;
enum class StencilOp : std::int32_t;
enum class StructureType : std::int32_t;
enum class SystemAllocationScope : std::int32_t;
enum class InternalAllocationType : std::int32_t;
enum class SamplerAddressMode : std::int32_t;
enum class Filter : std::int32_t;
enum class SamplerMipmapMode : std::int32_t;
enum class VertexInputRate : std::int32_t;
enum class PipelineStageFlagBits : std::int32_t;
enum class SparseImageFormatFlagBits : std::int32_t;
enum class SampleCountFlagBits : std::int32_t;
enum class AttachmentDescriptionFlagBits : std::int32_t;
enum class DescriptorPoolCreateFlagBits : std::int32_t;
enum class DependencyFlagBits : std::int32_t;
enum class ColorSpaceKHR : std::int32_t;
enum class CompositeAlphaFlagBitsKHR : std::int32_t;
enum class DisplayPlaneAlphaFlagBitsKHR : std::int32_t;
enum class PresentModeKHR : std::int32_t;
enum class SurfaceTransformFlagBitsKHR : std::int32_t;
enum class DebugReportFlagBitsEXT : std::int32_t;
enum class DebugReportObjectTypeEXT : std::int32_t;
enum class DebugReportErrorEXT : std::int32_t;


struct Offset2D;
struct Offset3D;
struct Extent2D;
struct Extent3D;
struct Viewport;
struct Rect2D;
struct Rect3D;
struct ClearRect;
struct ComponentMapping;
struct PhysicalDeviceProperties;
struct ExtensionProperties;
struct LayerProperties;
struct ApplicationInfo;
struct AllocationCallbacks;
struct DeviceQueueCreateInfo;
struct DeviceCreateInfo;
struct InstanceCreateInfo;
struct QueueFamilyProperties;
struct PhysicalDeviceMemoryProperties;
struct MemoryAllocateInfo;
struct MemoryRequirements;
struct SparseImageFormatProperties;
struct SparseImageMemoryRequirements;
struct MemoryType;
struct MemoryHeap;
struct MappedMemoryRange;
struct FormatProperties;
struct ImageFormatProperties;
struct DescriptorBufferInfo;
struct DescriptorImageInfo;
struct WriteDescriptorSet;
struct CopyDescriptorSet;
struct BufferCreateInfo;
struct BufferViewCreateInfo;
struct ImageSubresource;
struct ImageSubresourceLayers;
struct ImageSubresourceRange;
struct MemoryBarrier;
struct BufferMemoryBarrier;
struct ImageMemoryBarrier;
struct ImageCreateInfo;
struct SubresourceLayout;
struct ImageViewCreateInfo;
struct BufferCopy;
struct SparseMemoryBind;
struct SparseImageMemoryBind;
struct SparseBufferMemoryBindInfo;
struct SparseImageOpaqueMemoryBindInfo;
struct SparseImageMemoryBindInfo;
struct BindSparseInfo;
struct ImageCopy;
struct ImageBlit;
struct BufferImageCopy;
struct ImageResolve;
struct ShaderModuleCreateInfo;
struct DescriptorSetLayoutBinding;
struct DescriptorSetLayoutCreateInfo;
struct DescriptorPoolSize;
struct DescriptorPoolCreateInfo;
struct DescriptorSetAllocateInfo;
struct SpecializationMapEntry;
struct SpecializationInfo;
struct PipelineShaderStageCreateInfo;
struct ComputePipelineCreateInfo;
struct VertexInputBindingDescription;
struct VertexInputAttributeDescription;
struct PipelineVertexInputStateCreateInfo;
struct PipelineInputAssemblyStateCreateInfo;
struct PipelineTessellationStateCreateInfo;
struct PipelineViewportStateCreateInfo;
struct PipelineRasterizationStateCreateInfo;
struct PipelineMultisampleStateCreateInfo;
struct PipelineColorBlendAttachmentState;
struct PipelineColorBlendStateCreateInfo;
struct PipelineDynamicStateCreateInfo;
struct StencilOpState;
struct PipelineDepthStencilStateCreateInfo;
struct GraphicsPipelineCreateInfo;
struct PipelineCacheCreateInfo;
struct PushConstantRange;
struct PipelineLayoutCreateInfo;
struct SamplerCreateInfo;
struct CommandPoolCreateInfo;
struct CommandBufferAllocateInfo;
struct CommandBufferInheritanceInfo;
struct CommandBufferBeginInfo;
struct RenderPassBeginInfo;
union ClearColorValue;
struct ClearDepthStencilValue;
union ClearValue;
struct ClearAttachment;
struct AttachmentDescription;
struct AttachmentReference;
struct SubpassDescription;
struct SubpassDependency;
struct RenderPassCreateInfo;
struct EventCreateInfo;
struct FenceCreateInfo;
struct PhysicalDeviceFeatures;
struct PhysicalDeviceSparseProperties;
struct PhysicalDeviceLimits;
struct SemaphoreCreateInfo;
struct QueryPoolCreateInfo;
struct FramebufferCreateInfo;
struct DrawIndirectCommand;
struct DrawIndexedIndirectCommand;
struct DispatchIndirectCommand;
struct SubmitInfo;
struct DisplayPropertiesKHR;
struct DisplayPlanePropertiesKHR;
struct DisplayModeParametersKHR;
struct DisplayModePropertiesKHR;
struct DisplayModeCreateInfoKHR;
struct DisplayPlaneCapabilitiesKHR;
struct DisplaySurfaceCreateInfoKHR;
struct DisplayPresentInfoKHR;
struct SurfaceCapabilitiesKHR;
struct AndroidSurfaceCreateInfoKHR;
struct MirSurfaceCreateInfoKHR;
struct WaylandSurfaceCreateInfoKHR;
struct Win32SurfaceCreateInfoKHR;
struct XlibSurfaceCreateInfoKHR;
struct XcbSurfaceCreateInfoKHR;
struct SurfaceFormatKHR;
struct SwapchainCreateInfoKHR;
struct PresentInfoKHR;
struct DebugReportCallbackCreateInfoEXT;



}